company = '東武';
Dtype = [0, 0, 0];
detailflag = 2;
TableTitle = ['特急', '特急 日光 鬼怒川方面', '区間急行 区間準急 普通'];
RailNumberDevide(3, 2, 1);
DestinationDevide(['赤城', '太田', '伊勢崎', '葛生', '館林'], 1, 0);
limitednumber(TT[0], 1, 'りょうもう');
limitednumber(TT[1], 1, 'けごん');
limitednumber(TT[1], 1, 'きぬ');
limitednumber(TT[1], 1, 'スカイツリーライナー');
limitednumber(TT[1], 1, 'スペーシアＸ');
//TrainNameDevide(['普通','区間準急','区間急行'],1,2);
var staflag = 0;